	MOV TMOD,#20H ; 0010 0000 - TIMER 1 8 BIT AUTORELOAD TIMER
	MOV TH1,#0FAH ; BAUD RATE 9600 BITS PER SEC
	MOV SCON,#50H ; SERIAL MODE1 8 BIT ASYNCHRONOUS TRANSMISSION
	SETB TR1      ; START TIMER
START: CLR TI     ;CLEAR TRNSMIT FLAG
	MOV SBUF,#'E' ;SEND ASCII CHAR 'A'
LOOP:JNB TI,LOOP  ; TILL TI BECOMES 1 , THE TRANSMISSION SHOULD HAPPEN

	CLR TI     ;CLEAR TRNSMIT FLAG
	MOV SBUF,#'I' ;SEND ASCII CHAR 'A'
LOOP3:JNB TI,LOOP3

	CLR TI     ;CLEAR TRNSMIT FLAG
	MOV SBUF,#'E' ;SEND ASCII CHAR 'A'
LOOP1:JNB TI,LOOP1

    CLR TI     ;CLEAR TRNSMIT FLAG
	MOV SBUF,#' ' ;SEND ASCII CHAR 'A'
LOOP2:JNB TI,LOOP2
	
	SJMP START  
    END
		